### ISSUE TITLE
[Bug] Save without selecting a Magento Store in Store Relations return wrong url

### ISSUE THREAD

**Issue by simbus82** [yireo/MageBridgeCore#12]
If i go to Store Relations and save without selection a store i obtain this wrong url, without all "slashes".

![after-save-without-select-return-to-broken-link-2](https://cloud.githubusercontent.com/assets/1375730/19305291/81e8f930-9070-11e6-9724-e2afb929a16f.PNG)

When i go back, the action is saved and i see the correct page with correct notice for my error.

![after-save-without-select-return-to-broken-link](https://cloud.githubusercontent.com/assets/1375730/19305275/6e6dc502-9070-11e6-8c18-c5b0d2381403.PNG)

Thanks

**Comment by jissereitsma** [comment]
This bug is discussed here https://www.yireo.com/forum/magebridge-core/13408-problem-updating-to-1-9-5415/19729 and will be fixed in the next MageBridge build, accompanied with a Yireo Library update.

**Comment by simbus82** [comment]
Thanks!
