### ISSUE TITLE
[Bug] Class Model MagebridgeModelElement is not in file

### ISSUE THREAD

**Issue by simbus82** [yireo/MageBridgeCore#13]
Every time i'm going to create a menu voice "Magebridge Category" in Joomla and i go to select a Magento Category, i see this notice in the modal window.

![class-model-error](https://cloud.githubusercontent.com/assets/1375730/19305428/1ddef9de-9071-11e6-85a1-3a699b55b0f0.PNG)

Thanks

**Comment by jissereitsma** [comment]
I've tried to replicate this issue, but am unable to. The class `MagebridgeModelElement` indeed does not exist, but there is nowhere a reference to this class anyway. The latest MageBridge build relies on the Yireo Library. Could you verify that this is installed? It should be at version 0.2.10.

**Comment by simbus82** [comment]
![image](https://cloud.githubusercontent.com/assets/1375730/22198107/5e0b2f3e-e155-11e6-9aa2-68184f09a2f3.png)
Maybe this folder and others old folders and fiels need to be cleaned? I think Joomla is reading some old files...

**Comment by yireo** [comment]
There's quite some more changes. The `loader.php` file that you highlight in your screenshot should not contain any listing of files like the original `Element` classes (Joomla 1.5 legacy). The mentioned `loader.php` actually loads files from the Yireo Library, not MageBridge. An updated version (some weeks on GitHub already) makes all of the files in this `administrator/components/com_magebridge/libraries` folder obsolete by reusing the generic Yireo Library as a separate package. The file `components/com_magebridge/helpers/loader.php` was originally used (and is still used) for loading MageBridge-specific classes, but it contains nowhere this `MagebridgeModelElement` class. It could be that some old files are stuck in your environment, but the sources here online should be up-to-date.

**Comment by simbus82** [comment]
Is it possible in the installer, when we do an upgrade , check and remove old files?

**Comment by jissereitsma** [comment]
This is now included for the next MageBridge build: https://github.com/yireo/MageBridgeCore/commit/a7a833c31a4ed079785fefd253c60b14506833ab
