### ISSUE TITLE
[Bug] Default language string not loaded for com_magebridge_desc after install

### ISSUE THREAD

**Issue by simbus82** [yireo/MageBridgeCore#14]
After the installation of the component MageBridge i see the language constant without the correct default value (Example screenshot is in Italian)

![language-string-after-com-installation](https://cloud.githubusercontent.com/assets/1375730/19305555/ba7a56f8-9071-11e6-9b3e-0fa93d078f82.PNG)

I don't know if is it a bug or is needed an improvement, bur here i could expect a nice description of what i have installed ;-)

Thanks!

**Comment by jissereitsma** [comment]
Thanks for spotting this. This should be fixed with the next release. https://github.com/yireo/MageBridgeCore/commit/a0af45e39277a352b55f3a6e2e3dafa5b998305c
