### ISSUE TITLE
Product Compare wrong redirect

### ISSUE THREAD

**Issue by cinemarene** [yireo/MageBridgeCore#7]
I'm testing the Magebridge right now to find out if it is suitable for our company.

Now i stuck at adding products to "product_compare". If i want to add a product to the compare List by clicking the Button "Add to Compare", the Magebridge directly redirects to the Magento default page.

How to reproduce the Problem:
1. Go to "http://joomla1.magebridge.com/shop/electronics/cell-phones/nokia-2610-phone"
2. Click "Add to Compare" => redirects to "http://magento1.magebridge.com/"
3. Go back
4. You can see the notice that the product was added to the compare list.

Edit: same for remove product from compare list and clearing compare list.

**Comment by yireo** [comment]
We can confirm that this is an issue on this demo site, and we will schedule to fix this one day. Note that this does not occur anywhere else, so there is no bug report to here on this GitHub repository either. Also note that GitHub is used for coders. If you have PRs or want to discuss the code itself, feel free to comment here. However, if you are pointing to end-user issues, please see the following instead:
https://www.yireo.com/software/magebridge/products-and-pricing

**Comment by cinemarene** [comment]
Thank you for the quick reply.

Before buying a license i wanted to test the system with the free version from Github.
We created a testsystem on your server (Joomla 3.4.8 and Magento 1.9.0.1) with the latest version "1.9.5370" from GitHub.
After configuring the System with the documentation from "yireo.com" i was not able to fix that problem. Then i checked the demopage and there was the same issue.

Is the GitHub version the same version like the end-user version?

P.S: Its not possible to upgrade Magento to the latest version "1.9.2.3" due internal reasons. So, do i need the newest version of magento?

**Comment by yireo** [comment]
It might be a bug, but as long as we are not able to replicate this on other sites, we are not fixing it. The GitHub version is our only source for the MageBridge core. Please note that you can't buy a license from us - we don't sell it. We only sell support via support subscriptions. This issue is now closed, because it deals with a support request that needs to be dealt with differently.

**Comment by cinemarene** [comment]
Hello again,

i only want to say, it's working now.
After reading the Magebridge Documentation again, i found a misconfiguration through me.

Sorry for the wrong issue report.
